# Generated by Django 5.2.8 on 2025-11-14 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('restaurants', '0003_allergentag_cuisinetag_flavortag_mealtypetag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary / office'), ('light', 'Lightly active'), ('active', 'Active'), ('athlete', 'Athlete')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bmr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basal Metabolic Rate, internal use only', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='UserAllergenPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergen_prefs', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='restaurants.allergentag')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_allergens',
            field=models.ManyToManyField(blank=True, related_name='past_by_profiles', through='accounts.UserAllergenPreference', to='restaurants.allergentag'),
        ),
        migrations.CreateModel(
            name='UserCuisinePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_prefs', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='restaurants.cuisinetag')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_cuisines',
            field=models.ManyToManyField(blank=True, related_name='past_by_profiles', through='accounts.UserCuisinePreference', to='restaurants.cuisinetag'),
        ),
        migrations.CreateModel(
            name='UserFlavorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_prefs', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='restaurants.flavortag')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_flavors',
            field=models.ManyToManyField(blank=True, related_name='past_by_profiles', through='accounts.UserFlavorPreference', to='restaurants.flavortag'),
        ),
        migrations.CreateModel(
            name='UserMealTypePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealtype_prefs', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='restaurants.mealtypetag')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_meal_types',
            field=models.ManyToManyField(blank=True, related_name='past_by_profiles', through='accounts.UserMealTypePreference', to='restaurants.mealtypetag'),
        ),
        migrations.CreateModel(
            name='UserNutritionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_prefs', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='restaurants.nutritiontag')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_nutritions',
            field=models.ManyToManyField(blank=True, related_name='past_by_profiles', through='accounts.UserNutritionPreference', to='restaurants.nutritiontag'),
        ),
        migrations.CreateModel(
            name='UserProteinPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_prefs', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='restaurants.proteintag')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_proteins',
            field=models.ManyToManyField(blank=True, related_name='past_by_profiles', through='accounts.UserProteinPreference', to='restaurants.proteintag'),
        ),
        migrations.CreateModel(
            name='UserSpicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spice_prefs', to='accounts.userprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='restaurants.spicinesstag')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='past_spice_levels',
            field=models.ManyToManyField(blank=True, related_name='past_by_profiles', through='accounts.UserSpicePreference', to='restaurants.spicinesstag'),
        ),
    ]
