# Generated by Django 5.2.8 on 2025-11-14 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_item_unique_together_alter_restaurant_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuisineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlavorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MealTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpicinessTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='google_place_id',
            field=models.CharField(db_index=True, help_text='Google Places API place_id', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AddField(
            model_name='item',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='items', to='restaurants.allergentag'),
        ),
        migrations.AddField(
            model_name='item',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='items', to='restaurants.cuisinetag'),
        ),
        migrations.AddField(
            model_name='item',
            name='flavors',
            field=models.ManyToManyField(blank=True, related_name='items', to='restaurants.flavortag'),
        ),
        migrations.AddField(
            model_name='item',
            name='meal_types',
            field=models.ManyToManyField(blank=True, related_name='items', to='restaurants.mealtypetag'),
        ),
        migrations.AddField(
            model_name='item',
            name='nutritions',
            field=models.ManyToManyField(blank=True, related_name='items', to='restaurants.nutritiontag'),
        ),
        migrations.AddField(
            model_name='item',
            name='proteins',
            field=models.ManyToManyField(blank=True, related_name='items', to='restaurants.proteintag'),
        ),
        migrations.AddField(
            model_name='item',
            name='spiciness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='restaurants.spicinesstag'),
        ),
    ]
