# Generated by Django 5.2.8 on 2025-11-14 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_order_orderitem_order_restaurants_user_id_146122_idx_and_more'),
    ]

    operations = [
        
    ]
