# Generated by Django 5.2.8 on 2025-11-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_order_orderitem_order_restaurants_user_id_146122_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='spiciness',
            new_name='spice_levels',
        ),
    ]
