# Generated by Django 5.2.8 on 2025-11-20 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_spiciness_item_spice_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Restaurant owner (merchant account). Null for system/public restaurants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['owner', 'is_active'], name='restaurants_owner_i_283091_idx'),
        ),
    ]
